### ISSUE TITLE
Freeze with corrupted double-linked list on opening AI debug window

### ISSUE THREAD

**Issue by deraffe** [JGRennison/OpenTTD-patches#256]
## Version of OpenTTD
OpenTTD jgrpp-0.41.1
Linux x86_64

## Expected result
An AI script crash should open the AI debug window and allow me continue playing.

## Actual result
The AI script crash also freezes OpenTTD with `corrupted double-linked list`.

### OpenTTD log
```
dbg: [script] [2] [S] Your script made an error: parameter 1 has an invalid type 'null' ; expected: 'integer'
dbg: [script] [2] [S]
dbg: [script] [2] [S] *FUNCTION [SupplyDepot()] civilai-32/rv.nut line [753]
dbg: [script] [2] [S] *FUNCTION [MakeAPlan()] civilai-32/rv.nut line [716]
dbg: [script] [2] [S] *FUNCTION [CargoPlan()] civilai-32/rv.nut line [556]
dbg: [script] [2] [S] *FUNCTION [MainLoop()] civilai-32/main.nut line [175]
dbg: [script] [2] [S] *FUNCTION [Start()] civilai-32/main.nut line [130]
dbg: [script] [2] [S]
dbg: [script] [2] [S] [dosh] 1259187
dbg: [script] [2] [S] [rv] NULL
dbg: [script] [2] [S] [cargo] 11
dbg: [script] [2] [S] [ind] 209
dbg: [script] [2] [S] [this] INSTANCE
dbg: [script] [2] [S] [stop] NULL
dbg: [script] [2] [S] [search] INSTANCE
dbg: [script] [2] [S] [ilist] INSTANCE
dbg: [script] [2] [S] [tslist] INSTANCE
dbg: [script] [2] [S] [tslist] INSTANCE
dbg: [script] [2] [S] [cargo] 11
dbg: [script] [2] [S] [this] INSTANCE
dbg: [script] [2] [S] [food] 11
dbg: [script] [2] [S] [this] INSTANCE
dbg: [script] [2] [S] [dosh] 1261281
dbg: [script] [2] [S] [this] INSTANCE
dbg: [script] [2] [S] [this] INSTANCE
dbg: [script] The script died unexpectedly.
corrupted double-linked list
```

### `gdb` backtrace
```
Thread 20 "ottd:game" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffb9d1d640 (LWP 494550)]
0x00007ffff6f60ef5 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff6f60ef5 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff6f4a862 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff6fa2f38 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007ffff6faabea in  () at /usr/lib/libc.so.6
#4  0x00007ffff6fabacc in unlink_chunk.constprop () at /usr/lib/libc.so.6
#5  0x00007ffff6fabc29 in malloc_consolidate () at /usr/lib/libc.so.6
#6  0x00007ffff6fadb03 in _int_malloc () at /usr/lib/libc.so.6
#7  0x00007ffff6faf7a1 in malloc () at /usr/lib/libc.so.6
#8  0x00007ffff7571e38 in icu_69::UnicodeString::allocate(int) () at /usr/lib/libicuuc.so.69
#9  0x00007ffff7573b99 in icu_69::UnicodeString::cloneArrayIfNeeded(int, int, signed char, int**, signed char) () at /usr/lib/libicuuc.so.69
#10 0x00007ffff75757ef in icu_69::UnicodeString::getBuffer(int) () at /usr/lib/libicuuc.so.69
#11 0x00007ffff757596f in icu_69::UnicodeString::setToUTF8(icu_69::StringPiece) () at /usr/lib/libicuuc.so.69
#12 0x00007ffff7575b17 in icu_69::UnicodeString::fromUTF8(icu_69::StringPiece) () at /usr/lib/libicuuc.so.69
#13 0x00007ffff74fb67b in icu_69::RBBIDataWrapper::init(icu_69::RBBIDataHeader const*, UErrorCode&) () at /usr/lib/libicuuc.so.69
#14 0x00007ffff74fb80a in icu_69::RBBIDataWrapper::RBBIDataWrapper(UDataMemory*, UErrorCode&) () at /usr/lib/libicuuc.so.69
#15 0x00007ffff74f9c70 in icu_69::RuleBasedBreakIterator::RuleBasedBreakIterator(UDataMemory*, UErrorCode&) () at /usr/lib/libicuuc.so.69
#16 0x00007ffff74bb5c0 in icu_69::BreakIterator::buildInstance(icu_69::Locale const&, char const*, UErrorCode&) () at /usr/lib/libicuuc.so.69
#17 0x00007ffff74bba80 in icu_69::BreakIterator::makeInstance(icu_69::Locale const&, int, UErrorCode&) () at /usr/lib/libicuuc.so.69
#18 0x00000001006ee760 in IcuStringIterator::IcuStringIterator() ()
#19 0x00000001006edefd in StringIterator::Create() ()
#20 0x0000000100709519 in Textbuf::Textbuf(unsigned short, unsigned short) ()
#21 0x000000010031a23a in AIDebugWindow::AIDebugWindow(WindowDesc*, int) ()
#22 0x0000000100315409 in ShowAIDebugWindow(Owner) ()
#23 0x000000010032bf54 in AIInstance::Died() ()
#24 0x00000001002da0d1 in ScriptInstance::GameLoop() ()
#25 0x0000000100314998 in AI::GameLoop() ()
#26 0x0000000100608d5f in StateGameLoop() ()
#27 0x00000001006091f7 in GameLoop() ()
#28 0x0000000100490dba in VideoDriver::GameLoop() ()
#29 0x0000000100490e70 in VideoDriver::GameThread() ()
#30 0x00000001004917a6 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&)(VideoDriver*), VideoDriver*&&)#1}, char const*, void (*)(VideoDriver*), VideoDriver*> > >::_M_run() ()
#31 0x00007ffff731fbc4 in std::execute_native_thread_routine(void*) (__p=0x104fa6dd0) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#32 0x00007ffff7436299 in start_thread () at /usr/lib/libpthread.so.0
#33 0x00007ffff7023053 in clone () at /usr/lib/libc.so.6
```

## Steps to reproduce
Reproducing may be difficult, since you have to hit the right conditions for the AI to crash – but letting the savegame in [crash.zip](https://github.com/JGRennison/OpenTTD-patches/files/6479754/crash.zip) run for a while seems to work for me.

**Comment by JGRennison** [comment]
Thanks for reporting this, I have reproduced this issue in trunk so have raised an issue about it upstream.

**Comment by deraffe** [comment]
@JGRennison Thank you for writing filing a proper issue upstream… doing that would have meant a lot more effort for me. :-)
And kudos for your phenomenal work in maintaining this patchset.

**Comment by JGRennison** [comment]
This should be fixed in the most recent release.
