### ISSUE TITLE
Crash when train traverses signalled bridge

### ISSUE THREAD

**Issue by sammoth** [JGRennison/OpenTTD-patches#65]
I am getting this crash in this save game. I have narrowed it down and it seems to occur when a train is traversing the centred bridge which crosses the other lines, and it doesn't occur if I remove the signals from the bridge before the train crosses it. In this save the crash occurs on Aug 17. I have attached everything in case the crash save isn't enough. Thanks!

```
*** OpenTTD Crash Report ***

Crash at: Mon Aug 20 10:34:57 2018
In game date: 2122-08-14 (25, 0)

Crash reason:
 Signal:  Aborted (6)
          si_code: -6
 Message: Assertion failed at line 33 of /home/sam/.cache/aursync/openttd-jgrpp-git/src/OpenTTD-patches/src/tile_map.h: tile < MapSize()
	tile: 0x1003AC, size: 0x100000

Within context:
     0: CallVehicleTicks: veh: 219: (Train 28, c:0, st:FE, vs:D, vf:FTsa, gvf:, tf:, t:FF3B2)

OpenTTD version:
 Version:    jgrpp-0.26.2-22-ge789a6ff8 (0)
 NewGRF ver: 19006d64
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: Aug 20 2018 02:24:20
 Configure:  ./configure --prefix-dir=/usr --binary-name=openttd --binary-dir=bin --data-dir=share/openttd --install-dir=/home/sam/.cache/aursync/openttd-jgrpp-git/pkg/openttd-jgrpp-git --doc-dir=share/doc/openttd --menu-name=OpenTTD --personal-dir=.openttd

Stacktrace:
 [00]     0x557edd6efdc8 openttd                                  CrashLogUnix::LogStacktrace(char*, char const*) const + 0x148
 [01]     0x557edd57edda openttd                                  CrashLog::FillCrashLog(char*, char const*) const + 0x12a
 [02]     0x557edd57f151 openttd                                  CrashLog::MakeCrashLog() const + 0x91
 [03]     0x557edd6ef8d0 openttd                                  + 0x46d8d0
 [04]     0x7efef6ee23c0 /usr/lib/libpthread.so.0                 + 0x123c0
 [05]     0x7efef54e7d7f /usr/lib/libc.so.6                       gsignal + 0x10f
 [06]     0x7efef54d2672 /usr/lib/libc.so.6                       abort + 0x125
 [07]     0x557edd6d6af4 openttd                                  + 0x454af4
 [08]     0x557edd8bbc3b openttd                                  + 0x639c3b
 [09]     0x557edd8727fc openttd                                  + 0x5f07fc
 [10]     0x557edd87c216 openttd                                  TrainController(Train*, Vehicle*, bool) + 0x1446
 [11]     0x557edd87f8bf openttd                                  + 0x5fd8bf
 [12]     0x557edd87ff07 openttd                                  Train::Tick() + 0x77
 [13]     0x557edd89dd3b openttd                                  CallVehicleTicks() + 0x29b
 [14]     0x557edd6da5f9 openttd                                  StateGameLoop() + 0x119
 [15]     0x557edd6da906 openttd                                  GameLoop() + 0xa6
 [16]     0x557edd8b6a6b openttd                                  VideoDriver_SDL::MainLoop() + 0x21b
 [17]     0x557edd6d83bb openttd                                  openttd_main(int, char**) + 0x144b
 [18]     0x7efef54d4223 /usr/lib/libc.so.6                       __libc_start_main + 0xf3
 [19]     0x557edd4b915e openttd                                  _start + 0x2e

GDB info:
[New LWP 11032]
[New LWP 11035]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007efef6ee1184 in read () from /usr/lib/libpthread.so.0

Backtrace:
#0  0x00007efef6ee1184 in read () from /usr/lib/libpthread.so.0
No symbol table info available.
#1  0x0000557edd6ef984 in ?? ()
No symbol table info available.
#2  0x0000557edd6f0761 in CrashLogUnix::LogRegisters(char*, char const*) const ()
No symbol table info available.
#3  0x0000557edd57ef4c in CrashLog::FillCrashLog(char*, char const*) const ()
No symbol table info available.
#4  0x0000557edd57f151 in CrashLog::MakeCrashLog() const ()
No symbol table info available.
#5  0x0000557edd6ef8d0 in ?? ()
No symbol table info available.
#6  <signal handler called>
No symbol table info available.
#7  0x00007efef54e7d7f in raise () from /usr/lib/libc.so.6
No symbol table info available.
#8  0x00007efef54d2672 in abort () from /usr/lib/libc.so.6
No symbol table info available.
#9  0x0000557edd6d6af4 in assert_msg_error(int, char const*, char const*, char const*, char const*, ...) ()
No symbol table info available.
#10 0x0000557edd8bbc3b in MarkTileDirtyByTile(unsigned int, ZoomLevel, int) ()
No symbol table info available.
#11 0x0000557edd8727fc in ?? ()
No symbol table info available.
#12 0x0000557edd87c216 in TrainController(Train*, Vehicle*, bool) ()
No symbol table info available.
#13 0x0000557edd87f8bf in ?? ()
No symbol table info available.
#14 0x0000557edd87ff07 in Train::Tick() ()
No symbol table info available.
#15 0x0000557edd89dd3b in CallVehicleTicks() ()
No symbol table info available.
#16 0x0000557edd6da5f9 in StateGameLoop() ()
No symbol table info available.
#17 0x0000557edd6da906 in GameLoop() ()
No symbol table info available.
#18 0x0000557edd8b6a6b in VideoDriver_SDL::MainLoop() ()
No symbol table info available.
#19 0x0000557edd6d83bb in openttd_main(int, char**) ()
No symbol table info available.
#20 0x00007efef54d4223 in __libc_start_main () from /usr/lib/libc.so.6
No symbol table info available.
#21 0x0000557edd4b915e in _start ()
No symbol table info available.

Registers:
 rax:                0 rbx:              0x6 rcx:   0x7efef54e7d7f rdx:                0
 rsi:   0x7ffd58425f80 rdi:              0x2 rbp:   0x7ffd584261f0 rsp:   0x7ffd58425f80
 r8:                 0 r9:    0x7ffd58425f80 r10:              0x8 r11:            0x246
 r12:   0x7ffd584269ef r13:   0x557edd99d1d6 r14:                0 r15:   0x7efee9018d70
 rip:   0x7efef54e7d7f eflags:    0x246

Operating system:
 Name:     Linux
 Release:  4.17.13-arch1-1-ARCH
 Version:  #1 SMP PREEMPT Mon Aug 6 23:06:31 UTC 2018
 Machine:  x86_64
 Compiler: GCC 8.2.0 "8.2.0"

Distro version:
==> /etc/arch-release <==

Configuration:
 Blitter:      32bpp-sse2-anim
 Graphics set: original_dos (1)
 Language:     /usr/share/openttd/lang/english.lng
 Music driver: extmidi
 Music set:    NoMusic (0)
 Network:      no
 Sound driver: sdl
 Sound set:    OpenSFX (87)
 Video driver: sdl

Fonts:
 Small:  sprite
 Medium: sprite
 Large:  sprite
 Mono:   sprite

Map size: 0x100000 (1024 x 1024)

AI Configuration (local: 0) (current: 16):
  0: Human

Libraries:
 FontConfig: 2.13.0
 FreeType:   2.9.1
 ICU i18n:   62.1
 LZMA:       5.2.4
 LZO:        2.10
 PNG:        1.6.34
 SDL:        1.2.15
 Zlib:       1.2.11

---- gamelog start ----
Tick 0: new game started
Revision text changed to jgrpp-0.26.2, savegame version 200, not modified, _openttd_newgrf_version = 0x19006d64
New game mode: 2 landscape: 2
Added NewGRF: GRF ID 4A595001, checksum BBA9F50E894D063E20773A66E15B8FAD, filename: 2cc_bus_set-v10/2ccbusset.grf (md5sum matches)
Added NewGRF: GRF ID 4E4D0325, checksum DACB1F8EC7F42730F6AFBA6F1B0749ED, filename: 2cc_rapid_transit_for_me-1/2ccrtfm.grf (md5sum matches)
Added NewGRF: GRF ID 27711002, checksum 3E2A2578101FFB3DD8AFC451CC43C8D0, filename: 2cctrainset.grf (md5sum matches)
Added NewGRF: GRF ID 544D0101, checksum DB9858C96F754B9CFA029C88E75F6965, filename: 2cc_trainsinnml-3.0alpha2/2ccts.grf (md5sum matches)
Added NewGRF: GRF ID 4E4D0324, checksum F57F9543F06A27081A49B24D8B50273C, filename: 2cc_wagons_in_nml_2ccwin-1/2ccwin.grf (md5sum matches)
Added NewGRF: GRF ID 54446605, checksum A18BF2788AB874D65DD0DE3FAD9E50C9, filename: 1000building-set.grf (md5sum matches)
Added NewGRF: GRF ID 44440A01, checksum FCEEC76CF44EC23E7FE9C88048CF11CC, filename: av8_aviators_aircraft_set-2.21/pb_av8w.grf (md5sum matches)
Added NewGRF: GRF ID 19060801, checksum 6CFC6328D999C140851BFE6514BA277A, filename: bigger_depots.0.3/bigdepot.grf (md5sum matches)
Added NewGRF: GRF ID 4D420000, checksum BCB0AC917F3DA91A3197C6A07D06BCE8, filename: bobs_random_vehicles_-0.9/brbvw.grf (md5sum matches)
Added NewGRF: GRF ID 535A4005, checksum 698E571D5CB307AB649899A0F64FEC8B, filename: cars_cars-78/carscars.grf (md5sum matches)
Added NewGRF: GRF ID 52455400, checksum 1600687C50C5AB1E72EDD487CAD50E2A, filename: coded_by_aegir._artwork_by_aegir-1/ae_cityw.grf (md5sum matches)
Added NewGRF: GRF ID 52571203, checksum 7CE88A25DDB058C1BE577B88D049B274, filename: egrvts2-188/egrvts2.grf (md5sum matches)
Added NewGRF: GRF ID F1250007, checksum E3933F6F3FF709CA300D41308B0BE8BD, filename: firs_industry_replacement_set_3-3.0.10/firs.grf (md5sum matches)
Added NewGRF: GRF ID FBFB0301, checksum D961A46B2CC37A04CD4FCBEDD2311A53, filename: foobars_tram_tracks-1.0.1/foobarstramtracks.grf (md5sum matches)
Added NewGRF: GRF ID BEBE0200, checksum 63AA491A2FAE7D28F6D022F4585CCE31, filename: forestobjects.grf (md5sum matches)
Added NewGRF: GRF ID 24252C2C, checksum 4B9D9B1DF2B0C34FABC9AAC8554F9427, filename: hungarian_truck_set-3l/hts.grf (md5sum matches)
Added NewGRF: GRF ID 455B0101, checksum D224D77DBA44740B1DB42DCCAA67B25A, filename: indonesian_town_names-0.9/indonesia-beta-8.grf (md5sum matches)
Added NewGRF: GRF ID 4A430002, checksum 93EAC5F5396584B92D4C5F0AAAF3F6C5, filename: industrial_stations_renewal-1.0.2/indstatr.grf (md5sum matches)
Added NewGRF: GRF ID 504A0103, checksum 7040A4DC88302927794941CD853A47CF, filename: isrdock_v1_4.grf (md5sum matches)
Added NewGRF: GRF ID 504A0013, checksum E2FB4F9E66207F8016B7303323FDD00C, filename: isrdwe_objects_v1_0.grf (md5sum matches)
Added NewGRF: GRF ID 52453400, checksum B2E27B74A3894198A00139CFCF09D011, filename: japanese_buildings-3.1/jpbuild.grf (md5sum matches)
Added NewGRF: GRF ID 45530500, checksum D9BE5AFA481FC3E0A96E6EB72B455612, filename: japanese_stations-3.6/jpstations.grf (md5sum matches)
Added NewGRF: GRF ID 544B0202, checksum C336DF8D4ED416B99892E403303C9CA7, filename: korean_bus_set-0.3.6/ko_bus_set.grf (md5sum matches)
Added NewGRF: GRF ID 544B5555, checksum C6929AB705ECA51CF927718C23C1D826, filename: korea_train_set-1.5.11/ko_train_set.grf (md5sum matches)
Added NewGRF: GRF ID 4A4B0104, checksum 2C6AC8678B770815C2D55FE217EA3515, filename: lct_vehicle_set-v4/lctvehicles_v4.grf (md5sum matches)
Added NewGRF: GRF ID 44540000, checksum 827631B2FEEED78400419E98877F3331, filename: lithuanian_transportation_set.beta_1.1/ltts - beta 1.1w.grf (md5sum matches)
Added NewGRF: GRF ID 6D620C00, checksum 63B368A4B96038633CD48EE878C82927, filename: marico.grf (md5sum matches)
Added NewGRF: GRF ID 6D620004, checksum 663C139E24EE87C2EF6FB029C1AB3CED, filename: newships.grf (md5sum matches)
Added NewGRF: GRF ID 6D620601, checksum 537A2B9E5F0644BC360248B2B802D086, filename: newstats.grf (md5sum matches)
Added NewGRF: GRF ID 44440302, checksum C2A2CE006D0F3BC2E44122A9358EC999, filename: north_american_renewal_set-2.51/newnars.grf (md5sum matches)
Added NewGRF: GRF ID 454E2501, checksum 2FD71110A9F9CA2A667C9A21AA84C8B0, filename: north_korean_road_vehicle_set-1.1/dprkroad.grf (md5sum matches)
Added NewGRF: GRF ID 444A5401, checksum B9E9E16F258B32DC91E8BABEF037AFA7, filename: nutracks-r247/nutracks.grf (md5sum matches)
Added NewGRF: GRF ID 49464E4F, checksum BAC22546C151037276AA7775F17AB3A9, filename: SNO-Supercheese'sNewObjects.grf (md5sum matches)
Added NewGRF: GRF ID 50430306, checksum 8DBA32434A46D758917FB4A5A6BDDC03, filename: south_korean_town_names-1.0/skoreatowns.grf (md5sum matches)
Added NewGRF: GRF ID 414E0201, checksum 0DA3A80B986BC3C17C20CA4CE9CA26AA, filename: fish_2-2.0.3/fish.grf (md5sum matches)
Added NewGRF: GRF ID 52455300, checksum 37C0B839B13C4B18051580C81EEDF427, filename: suburban_stations-1/ae_subuw.grf (md5sum matches)
Added NewGRF: GRF ID 56430001, checksum 2AD089EE6B73F25D79F286AD43765914, filename: total_town_replacement_set-3.14/ttrs3w.grf (md5sum matches)
Added NewGRF: GRF ID 74677462, checksum 1D2A4E03D9F30922788C166254C27619, filename: total_bridge_renewal_set-1.2/total_bridges.grf (md5sum matches)
Added NewGRF: GRF ID 4A4B0102, checksum A4AA97ECC8829FDC455017BA75242298, filename: korean_bus_set_expansion-v1.15.2/kbs_expand_1.15.2.grf (md5sum matches)
Added NewGRF: GRF ID 444E0800, checksum 334F8C4697455569073434DB107F864A, filename: vast_objects-0.3.0/vastobjects.grf (md5sum matches)
Added NewGRF: GRF ID 444E0400, checksum 735D3D74D5DCADBF1FD6EF7A9C5A3519, filename: vast_station_tiles-0.2.0/vast.grf (md5sum matches)
Added NewGRF: GRF ID 444E0C00, checksum B5D2AB5FC93A09E1FAB5F0DB82307ECF, filename: vast_fences-0.2.0/vastfences.grf (md5sum matches)
Added NewGRF: GRF ID 57A50001, checksum 318F3C3F17CA68EAD533BAC88B093094, filename: was_world_airliners_set-0.1/was.grf (md5sum matches)
Added NewGRF: GRF ID 43415000, checksum 4DA9FE9A87DD330EBAD43916771BAF21, filename: opengfx_airports-0.4.2/ogfx-airports.grf (md5sum matches)
Added NewGRF: GRF ID 4F472B32, checksum B46F2D7781158DD122F2E4B2AFC9F38F, filename: opengfx_road_vehicles-0.4.1/ogfx-rv.grf (md5sum matches)
Added NewGRF: GRF ID 4F472B31, checksum 4E0B2D42462F295F36AFBA90D239A323, filename: opengfx_trains-0.3.0/ogfx-trains.grf (md5sum matches)
Added NewGRF: GRF ID 4F472B34, checksum 136D889FDAEAA3491F8320248A04425C, filename: opengfx_landscape-1.1.2/ogfx-landscape.grf (md5sum matches)
Added NewGRF: GRF ID 444C1105, checksum 4AC44465E334F062F56BC24C728C8E72, filename: dach_trains-0.3.2/dach.grf (md5sum matches)
Added NewGRF: GRF ID FBFB0601, checksum E167E84751FD2E61967944010AF5C56D, filename: dutch_trainset_2-2.1.0/dutchtrains.grf (md5sum matches)
Added NewGRF: GRF ID 4A560101, checksum 6A9F478B12CED677D71DE276ABB137D2, filename: finnish_trainset-0.5.8/finnishtrainset.grf (md5sum matches)
Added NewGRF: GRF ID 535A0D00, checksum 21AC703CAB2BE6A80FAF2344366FE0C1, filename: japanese_train_set-3.3/jptrains.grf (md5sum matches)
Added NewGRF: GRF ID 130C0000, checksum ADC6C63BA4636C5745F565648523D790, filename: las_train_pack__korea_train-2.2.1/newpackw.grf (md5sum matches)
Added NewGRF: GRF ID 41490006, checksum 37860FF76C7645EFD0B8B1B2D26BAF05, filename: swedish_trains.7.3/ai_swedish.grf (md5sum matches)
Added NewGRF: GRF ID 41533031, checksum B21E7D6ADD69B1C07643939764FB4878, filename: swedish_houses-1.1.2/swehouses.grf (md5sum matches)
Tick 1280: game loaded
New game mode: 1 landscape: 2
Tick 28615: settings changed
Setting changed: construction.command_pause_level : 1 -> 3
Tick 31254: settings changed
Setting changed: station.never_expire_airports : 0 -> 1
Tick 52878: settings changed
Setting changed: vehicle.wagon_speed_limits : 1 -> 0
Tick 7675: settings changed
Setting changed: vehicle.freight_trains : 1 -> 2
Tick 7681: settings changed
Setting changed: vehicle.freight_trains : 2 -> 3
Tick 7687: settings changed
Setting changed: vehicle.freight_trains : 3 -> 4
Tick 7693: settings changed
Setting changed: vehicle.freight_trains : 4 -> 5
Tick 7699: settings changed
Setting changed: vehicle.freight_trains : 5 -> 6
Tick 7705: settings changed
Setting changed: vehicle.freight_trains : 6 -> 7
Tick 7711: settings changed
Setting changed: vehicle.freight_trains : 7 -> 8
Tick 7717: settings changed
Setting changed: vehicle.freight_trains : 8 -> 9
Tick 24686: settings changed
Setting changed: vehicle.plane_speed : 1 -> 2
Tick 24692: settings changed
Setting changed: vehicle.plane_speed : 2 -> 3
Tick 24698: settings changed
Setting changed: vehicle.plane_speed : 3 -> 4
Tick 25081: settings changed
Setting changed: vehicle.plane_speed : 4 -> 3
Tick 25087: settings changed
Setting changed: vehicle.plane_speed : 3 -> 2
Tick 25093: settings changed
Setting changed: vehicle.plane_speed : 2 -> 1
Tick 62689: settings changed
Setting changed: vehicle.wagon_speed_limits : 0 -> 1
Tick 22770: game loaded
Revision text changed to jgrpp-0.26.2-22-ge789a6ff8, savegame version 200, not modified, _openttd_newgrf_version = 0x19006d64
---- gamelog end ----

Recent news messages:
(2122-08-04) StringID: 637, Type: 0, Ref1: 2, 219, Ref2: 3, 48
(2122-08-04) StringID: 694, Type: 10, Ref1: 2, 63, Ref2: 0, 4294967295
(2122-08-04) StringID: 694, Type: 10, Ref1: 2, 66, Ref2: 0, 4294967295
(2122-08-11) StringID: 694, Type: 10, Ref1: 2, 242, Ref2: 0, 4294967295

Command Log:
 Showing most recent 2 of 2 commands
   0 | 2122-07-11, 69,   0 | -m----- |        0 x       0, p1: 0x00000001, p2: 0x00000000, cc:  0, lc:  0, cmd: 0x0000003E (CmdPause)
   1 | 2122-07-11, 69,   0 | -m----- |        0 x       0, p1: 0x00000002, p2: 0x00000000, cc:  0, lc:  0, cmd: 0x0000003E (CmdPause)

*** End of OpenTTD Crash Report ***
`
[crash.zip](https://github.com/JGRennison/OpenTTD-patches/files/2302052/crash.zip)
``

**Comment by JGRennison** [comment]
Thanks for the bug report, this should be fixed now.
