### ISSUE TITLE
'Start Date' crash

### ISSUE THREAD

**Issue by tnnrht** [JGRennison/OpenTTD-patches#7]
On a new vehicle without any orders, clicking 'Start Date' crashes the game.
crash.log:
```
*** OpenTTD Crash Report ***

Crash at: Mon May  9 22:18:59 2016
In game date: 1950-01-01 (0, 0)

Crash reason:
 Signal:  Segmentation fault (11)
 Message: <none>

OpenTTD version:
 Version:    jgrpp-0.13.1 (0)
 NewGRF ver: 17006ba3
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: May  9 2016 15:17:21

Stacktrace (GDB):
[New LWP 12326]
[New LWP 12323]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fa8cc0fd3bd in read () at ../sysdeps/unix/syscall-template.S:81
#0  0x00007fa8cc0fd3bd in read () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x0000000000782ed9 in CrashLogUnix::LogStacktrace ()
No locals.
#2  0x0000000000659382 in CrashLog::FillCrashLog ()
No locals.
#3  0x00000000006595ef in CrashLog::MakeCrashLog ()
No locals.
#4  0x0000000000782b15 in HandleCrash ()
No locals.
#5  <signal handler called>
No locals.
#6  0x00000000007741d0 in OrderList::IsCompleteTimetable ()
No locals.
#7  0x00000000008a40b4 in TimetableWindow::OnClick ()
No locals.
#8  0x0000000000928b43 in HandleMouseEvents ()
No locals.
#9  0x0000000000902a16 in VideoDriver_SDL::PollEvent ()
No locals.
#10 0x0000000000902ca0 in VideoDriver_SDL::MainLoop ()
No locals.
#11 0x000000000076f982 in openttd_main ()
No locals.
#12 0x00007fa8c994eec5 in __libc_start_main (main=0x54f8c0 <main()>, argc=1, argv=0x7ffc6b8606e8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc6b8606d8) at libc-start.c:287
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 744902809320049992, 5952821, 140722112431840, 0, 0, -743452222513853112, -790383927967855288}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x92a870 <__libc_csu_init>, 0x7ffc6b8606e8}, data = {prev = 0x0, cleanup = 0x0, canceltype = 9611376}}}
        not_first_call = <optimized out>
#13 0x00000000005ad55e in _start ()
No symbol table info available.

Stacktrace:
 [00]           0x782d60 ./openttd                                CrashLogUnix::LogStacktrace(char*, char const*) const + 0x190
 [01]           0x659382 ./openttd                                CrashLog::FillCrashLog(char*, char const*) const + 0x112
 [02]           0x6595ef ./openttd                                CrashLog::MakeCrashLog() const + 0x7f
 [03]           0x782b15 ./openttd                                + 0x382b15
 [04]     0x7fa8c9963d40 /lib/x86_64-linux-gnu/libc.so.6          + 0x36d40
 [05]           0x7741d0 ./openttd                                OrderList::IsCompleteTimetable() const + 0x0
 [06]           0x8a40b4 ./openttd                                TimetableWindow::OnClick(Point, int, int) + 0x534
 [07]           0x928b43 ./openttd                                HandleMouseEvents() + 0x1173
 [08]           0x902a16 ./openttd                                VideoDriver_SDL::PollEvent() + 0xf6
 [09]           0x902ca0 ./openttd                                VideoDriver_SDL::MainLoop() + 0x80
 [10]           0x76f982 ./openttd                                openttd_main(int, char**) + 0x1442
 [11]     0x7fa8c994eec5 /lib/x86_64-linux-gnu/libc.so.6          __libc_start_main + 0xf5
 [12]           0x5ad55e ./openttd                                + 0x1ad55e

Operating system:
 Name:     Linux
 Release:  3.13.0-85-generic
 Version:  #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016
 Machine:  x86_64
 Compiler: GCC 4.8.4 "4.8.4"

Configuration:
 Blitter:      32bpp-sse2-anim
 Graphics set: OpenGFX (5580)
 Language:     /home/tnnrht/games/openttd/jgr/lang/english.lng
 Music driver: extmidi
 Music set:    NoMusic (0)
 Network:      no
 Sound driver: sdl
 Sound set:    OpenSFX (87)
 Video driver: sdl

Fonts:
 Small:  MS Gothic
 Medium: MS Gothic
 Large:  MS Gothic
 Mono:   sprite

AI Configuration (local: 0) (current: 0):
  0: Human

Libraries:
 Allegro:    Allegro 4.4.2, Unix
 FontConfig: 2.11.0
 FreeType:   2.5.2
 ICU i18n:   52.1
 ICU lx:     52.1
 LZMA:       5.1.0alpha
 LZO:        2.06
 PNG:        1.2.50
 SDL:        1.2.15
 Zlib:       1.2.8

---- gamelog start ----
Tick 0: new game started
Revision text changed to jgrpp-0.13.1, savegame version 194, not modified, _openttd_newgrf_version = 0x17006ba3
New game mode: 1 landscape: 0
---- gamelog end ----

*** End of OpenTTD Crash Report ***
```

**Comment by JGRennison** [comment]
Thanks for reporting this.
This is now fixed in commit f82673bed845d166935ffa7ff7d24ba3876ce221.
