### ISSUE TITLE
[Crash]: Crash when company gets sold/liquidated

### ISSUE THREAD

**Issue by RAD750** [JGRennison/OpenTTD-patches#783]
### Version of OpenTTD

OpenTTD 0.63.0 (Linux Mint)

### Steps to reproduce

1. Open attached savegame (too big to upload, see: https://www.mediafire.com/file/dkugl55gnyyw8z2/autosave3.sav/file) 
2. Click "Yes" when prompted to buy the company named ATC
3. OpenTTD crashes immediately

gdb debugging:
```
jacopo@prodesk:~$ gdb openttd 
GNU gdb (Ubuntu 15.0.50.20240403-0ubuntu1) 15.0.50.20240403-git
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from openttd...
(gdb) r
Starting program: /usr/games/openttd 
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/liballeg.so.4.4
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/liblber.so.2
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libbrotlidec.so.1
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libglib-2.0.so.0
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libpulse-simple.so.0
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libpulse.so.0
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libjack.so.0
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgmodule-2.0.so.0
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgobject-2.0.so.0
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libbrotlicommon.so.1
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-16.1.so
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libtinfo.so.6
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libcap.so.2
[New Thread 0x7fffeaa006c0 (LWP 121633)]
[New Thread 0x7fffea0006c0 (LWP 121634)]
[New Thread 0x7fffe96006c0 (LWP 121635)]
[New Thread 0x7fffe8c006c0 (LWP 121636)]
[New Thread 0x7fffe3e006c0 (LWP 121637)]
[New Thread 0x7fffe34006c0 (LWP 121638)]
[New Thread 0x7fffe2a006c0 (LWP 121639)]
[New Thread 0x7fffe20006c0 (LWP 121640)]
[New Thread 0x7fffe16006c0 (LWP 121641)]
[Thread 0x7fffe16006c0 (LWP 121641) exited]
[Thread 0x7fffe20006c0 (LWP 121640) exited]
[Thread 0x7fffe2a006c0 (LWP 121639) exited]
[New Thread 0x7fffe2a006c0 (LWP 121643)]
[New Thread 0x7fffe20006c0 (LWP 121644)]
[New Thread 0x7fffe16006c0 (LWP 121645)]
[New Thread 0x7fffd72006c0 (LWP 121646)]
[New Thread 0x7fffd68006c0 (LWP 121647)]
[New Thread 0x7ffff22556c0 (LWP 121648)]
[New Thread 0x7fffd5e006c0 (LWP 121649)]
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/allegro/4.4.3/alleg-dga2.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/allegro/4.4.3/alleg-alsadigi.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/allegro/4.4.3/alleg-alsamidi.so
[New Thread 0x7fffd54006c0 (LWP 121651)]
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pipewire.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/spa-0.2/support/libspa-support.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/spa-0.2/support/libspa-journal.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/spa-0.2/support/libspa-dbus.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-rt.so
[New Thread 0x7fffd4a006c0 (LWP 121652)]
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-protocol-native.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-client-node.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-client-device.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-adapter.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-metadata.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-session-manager.so
[New Thread 0x7fffbfe006c0 (LWP 121653)]
[New Thread 0x7fffbf4006c0 (LWP 121654)]
[Thread 0x7fffbf4006c0 (LWP 121654) exited]
[Thread 0x7fffbfe006c0 (LWP 121653) exited]
[Thread 0x7fffd4a006c0 (LWP 121652) exited]
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/spa-0.2/support/libspa-dbus.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-rt.so
[New Thread 0x7fffd4a006c0 (LWP 121656)]
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-protocol-native.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-client-node.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-client-device.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-adapter.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-metadata.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-session-manager.so
[New Thread 0x7fffbfe006c0 (LWP 121657)]
[New Thread 0x7fffbf4006c0 (LWP 121658)]
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/alsa-lib/libasound_module_ctl_pipewire.so
[New Thread 0x7fffbea006c0 (LWP 121659)]
[New Thread 0x7fffbe0006c0 (LWP 121661)]
[New Thread 0x7fffbd6006c0 (LWP 121662)]
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/spa-0.2/audioconvert/libspa-audioconvert.so
dbg: [driver:0] allegro: no midi card found
[New Thread 0x7fffbcc006c0 (LWP 121664)]
[New Thread 0x7fffb3e006c0 (LWP 121665)]
[New Thread 0x7fffb34006c0 (LWP 121666)]
[New Thread 0x7fffb2a006c0 (LWP 121667)]
[New Thread 0x7fffb20006c0 (LWP 121668)]
[New Thread 0x7fffb16006c0 (LWP 121669)]
[New Thread 0x7fffb0c006c0 (LWP 121670)]
[New Thread 0x7fffa7e006c0 (LWP 121671)]
[Thread 0x7fffa7e006c0 (LWP 121671) exited]
[New Thread 0x7fffa7e006c0 (LWP 121672)]
[New Thread 0x7fffa74006c0 (LWP 121673)]
[New Thread 0x7fffa6a006c0 (LWP 121674)]
[New Thread 0x7fffa60006c0 (LWP 121675)]
[New Thread 0x7fffa56006c0 (LWP 121676)]
[New Thread 0x7fffa4c006c0 (LWP 121677)]
[New Thread 0x7fff9be006c0 (LWP 121678)]
[New Thread 0x7fff9b4006c0 (LWP 121679)]
[New Thread 0x7fff9aa006c0 (LWP 121680)]
[New Thread 0x7fff9a0006c0 (LWP 121681)]
[New Thread 0x7fff996006c0 (LWP 121682)]
[New Thread 0x7fff98c006c0 (LWP 121683)]
[New Thread 0x7fff8fe006c0 (LWP 121684)]
[New Thread 0x7fff8f4006c0 (LWP 121685)]
[New Thread 0x7fff8ea006c0 (LWP 121686)]
[New Thread 0x7fff8e0006c0 (LWP 121687)]
[New Thread 0x7fff8d6006c0 (LWP 121688)]
[Thread 0x7fff8d6006c0 (LWP 121688) exited]
[Thread 0x7fff8f4006c0 (LWP 121685) exited]
[Thread 0x7fff8fe006c0 (LWP 121684) exited]
[Thread 0x7fff996006c0 (LWP 121682) exited]
[Thread 0x7fff9a0006c0 (LWP 121681) exited]
[Thread 0x7fff98c006c0 (LWP 121683) exited]
[Thread 0x7fff8ea006c0 (LWP 121686) exited]
[Thread 0x7fff8e0006c0 (LWP 121687) exited]
[New Thread 0x7fff8e0006c0 (LWP 121690)]
[Thread 0x7fff8e0006c0 (LWP 121690) exited]
[New Thread 0x7fff8e0006c0 (LWP 121707)]
[Thread 0x7fff8e0006c0 (LWP 121707) exited]
[New Thread 0x7fff8ea006c0 (LWP 121712)]
[Thread 0x7fff8ea006c0 (LWP 121712) exited]
[New Thread 0x7fff8ea006c0 (LWP 121714)]
[Thread 0x7fff8ea006c0 (LWP 121714) exited]
[New Thread 0x7fff8ea006c0 (LWP 121726)]
[New Thread 0x7fff8e0006c0 (LWP 121727)]
[New Thread 0x7fff98c006c0 (LWP 121728)]
[Thread 0x7fff8ea006c0 (LWP 121726) exited]
[Thread 0x7fff98c006c0 (LWP 121728) exited]
[Thread 0x7fff8e0006c0 (LWP 121727) exited]
[New Thread 0x7fff8f4006c0 (LWP 121729)]
[Thread 0x7fff8f4006c0 (LWP 121729) exited]
Error: Assertion failed at line 515 of /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/roadstop.cpp: temp.length == this->length && temp.occupied == this->occupied
length: 16 == 16, occupied: 0 == 6, xy: D23C31, index: 6

Thread 1 "openttd" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimised out>)
    at ./nptl/pthread_kill.c:44
warning: 44	./nptl/pthread_kill.c: File o directory non esistente
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimised out>)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimised out>)
    at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimised out>, signo=signo@entry=6)
    at ./nptl/pthread_kill.c:89
#3  0x00007ffff684526e in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#4  0x00007ffff68288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000555555813af2 in DoOSAbort ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/os/unix/unix.cpp:271
#6  0x0000555555ed2371 in fatalerror_common ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/openttd.cpp:173
#7  FatalErrorI ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/openttd.cpp:185
#8  0x0000555555d0ebdb in assert_str_error ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/error.cpp:27
#9  0x0000555555ccaf83 in AssertMsgErrorVFmt ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/debug.cpp:458
#10 0x0000555555f6d0f1 in AssertMsgError<int&, int const&, int&, int const&, unsigned int const&, unsigned short const&> ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/debug.h:123
--Type <RET> for more, q to quit, c to continue without paging--
#11 RoadStop::Entry::CheckIntegrity ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/roadstop.cpp:515
#12 0x0000555555c5a4d9 in CheckCaches(bool, std::function<void (std::basic_string_view<char, std::char_traits<char> >)>, CheckCachesFlags) ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/cachecheck.cpp:286
#13 0x0000555555cf86fc in PostAcquireCompany ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/economy.cpp:2556
#14 0x0000555555cfce83 in CmdBuyCompany ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/economy.cpp:2692
#15 0x0000555555c7a470 in Command::Execute ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/command_type.h:699
#16 DoCommandPInternal ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/command.cpp:1242
#17 0x0000555555c7ac72 in DoCommandPEx ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/command.cpp:1000
#18 0x0000555555c8d7ae in DoCommandP ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/command_func.h:56
#19 BuyCompanyWindow::OnClick ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/company_gui.cpp:2861
--Type <RET> for more, q to quit, c to continue without paging--
#20 BuyCompanyWindow::OnClick ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/company_gui.cpp:2853
#21 0x000055555618174d in DispatchLeftClickEvent ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/window.cpp:751
#22 MouseLoop ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/window.cpp:3074
#23 HandleMouseEvents ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/window.cpp:3174
#24 0x0000555555c255a5 in VideoDriver_SDL_Base::PollEvent ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/video/sdl2_v.cpp:715
#25 0x0000555555c28cbd in VideoDriver::Tick ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/video/video_driver.cpp:165
#26 0x0000555555c245de in VideoDriver_SDL_Base::LoopOnce ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/video/sdl2_v.cpp:987
#27 VideoDriver_SDL_Base::LoopOnce ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/video/sdl2_v.cpp:960
#28 VideoDriver_SDL_Base::MainLoop ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/video/sdl2_v.cpp:--Type <RET> for more, q to quit, c to continue without paging--
1005
#29 0x0000555555ed7406 in openttd_main ()
    at /home/jacopo/Scaricati/OpenTTD-patches-jgrpp-0.63.0/src/openttd.cpp:1020
#30 0x00007ffff682a1ca in __libc_start_call_main
    (main=main@entry=0x55555583ef60 <main()>, argc=argc@entry=1, argv=argv@entry=0x7fffffffdc98) at ../sysdeps/nptl/libc_start_call_main.h:58
#31 0x00007ffff682a28b in __libc_start_main_impl
    (main=0x55555583ef60 <main()>, argc=1, argv=0x7fffffffdc98, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffffffdc88) at ../csu/libc-start.c:360
#32 0x00005555558d5235 in _start ()
(gdb) k
Kill the program being debugged? (y or n) y
[Inferior 1 (process 121621) killed]
(gdb) 
```

thanks

### Upload crash files

[crash.zip](https://github.com/user-attachments/files/17924230/crash.zip)

**Comment by RAD750** [comment]
Seems to be fixed. While you're at it, would it be possible to add prebuilt images for Mint 22 (based on Ubuntu Noble 24.04), as on both Noble and Mint 22 you cannot install any of the available packages due to differences in some libraries and I have to compile them myself (for me it's fine, for my friends... not so much)

**Comment by JGRennison** [comment]
Have you tried using the generic build: <https://github.com/JGRennison/OpenTTD-patches/releases/download/jgrpp-0.63.1/openttd-jgrpp-0.63.1-linux-generic-amd64.tar.xz>

This ought to work without any package problems on those distro versions.

**Comment by RAD750** [comment]
That also works, but it has no menus or desktop files (naturally)
I think providing a build for Noble would be a good idea especially because Focal will be EOL very soon.

**Comment by RAD750** [comment]
Thank you! Also I can report the bug is fixed, we were able to purchase the bankrupt company without any crashes.
